heat_template_version: 2016-10-14
description: |
  Simple child-template to attach a volume to a server.
  Depends on parent template to feed instance_uuid.
  Intended to be executed with Rackspace Orchestration

parameters:
  volume_name:
    type: string
    description: name of volume to create

  instance_uuid:
    type: string
    description: UUID of instance to attach volume

  parent_stack_id:
    type: string
    default: None

  volume_type:
    type: string
    description: type of volume to build

  volume_size:
    type: number
    description: size of volume to build

resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      name: { get_param: volume_name }
      size: { get_param: volume_size }
      volume_type: { get_param: volume_type }
      metadata:
        rax-heat: { get_param: "parent_stack_id" }

  attach_volume:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_param: instance_uuid }
